name: Deploy Portfolio to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajustez selon la version Node.js de votre projet
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }} # Ex. : ftp.votredomaine.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21 # Port par défaut pour FTP
          protocol: ftp # Utilisation explicite de FTP
          local-dir: ./dist/ # Dossier généré par npm run build
          server-dir: ${{ secrets.REMOTE_DIR }} # Ex. : /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**